### ISSUE TITLE
Missing filter requirement

### ISSUE THREAD

**Issue by axelolsson** [chas-academy/09-recipe-book-Oleg-Lopes#1]
To pass fix this:
- [x] Kunna filtrera förslagen av recept på måltidstyp, allergener och tillagningstid 
- [ ] Mobilanpassad layout 
- [ ] Layout/disposition skapad i Bootstrap eller valfritt CSS ramverk

Also update your dependencies while you're at it.

**Comment by Oleg-Lopes** [comment]
Filtering by diet labels checked.
Implemented at http://oleglopes.chas.academy/recipe-app/
https://github.com/chas-academy/10-recipe-app-Oleg-Lopes/
